Repository open-feature/flagd, pull requests merged in 2024-06, with the labels that each got.

#1322 fix: fixes store merge when selector is used
  core/pkg/evaluator/json.go
  core/pkg/evaluator/json_test.go
  core/pkg/model/flag.go
  core/pkg/store/flags.go
  core/pkg/store/flags_test.go
  core/pkg/sync/grpc/grpc_sync.go
  core/pkg/sync/isync.go
Labels: size:L

#1326 feat: support `FLAGD_DEBUG` / `--debug` / `-x`
  docs/troubleshooting.md
  flagd/cmd/root.go
Labels: size:XS

#1325 fix: readable error messages
  core/pkg/model/error.go
  flagd/pkg/service/flag-evaluation/flag_evaluator.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_test.go
Labels: size:M

#1329 chore: fix renovate by setting correct renovate constrant
  renovate.json
Labels: size:XS

#1339 feat: add mandatory flags property in bulk response
  core/pkg/service/ofrep/models.go
  core/pkg/service/ofrep/models_test.go
Labels: size:M

#1313 feat: support relative weighting for fractional evaluation
  core/pkg/evaluator/fractional.go
  core/pkg/evaluator/fractional_test.go
  docs/reference/custom-operations/fractional-operation.md
  docs/reference/specifications/custom-operations/fractional-operation-spec.md
Labels: size:L

#1338 feat!: support emitting errors from the bulk evaluator
  core/pkg/evaluator/fractional.go
  core/pkg/evaluator/ievaluator.go
  core/pkg/evaluator/json.go
  core/pkg/evaluator/json_test.go
  core/pkg/evaluator/mock/ievaluator.go
  core/pkg/service/ofrep/models.go
  core/pkg/store/flags.go
  flagd/pkg/service/flag-evaluation/flag_evaluator.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_test.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_v2_test.go
  flagd/pkg/service/flag-evaluation/ofrep/handler.go
  flagd/pkg/service/flag-evaluation/ofrep/handler_test.go
  flagd/pkg/service/flag-evaluation/ofrep/ofrep_service_test.go
  flagd/pkg/service/flag-sync/sync-multiplexer.go
Labels: size:L
