Repository open-feature/flagd, pull requests merged in 2024-08, with the labels that each got.

#1375 chore: improve gRPC sync service shutdown behavior
  flagd/pkg/service/flag-sync/sync_service.go
Labels: size:XS

#1365 feat: add 'watcher' interface to file sync
  core/pkg/sync/builder/syncbuilder.go
  core/pkg/sync/file/fileinfo_watcher.go
  core/pkg/sync/file/fileinfo_watcher_test.go
  core/pkg/sync/file/filepath_sync.go
  core/pkg/sync/file/fsnotify_watcher.go
  docs/reference/sync-configuration.md
Labels: size:XL

#1394 docs: update playground libraries
  docs/playground/playground.js
  playground-app/package-lock.json
  playground-app/package.json
Labels: size:S
