Repository open-feature/flagd, pull requests merged in 2024-07, with the labels that each got.

#1352 fix: invalid scoped-sync responses for empty flags
  flagd/pkg/service/flag-sync/sync-multiplexer.go
  flagd/pkg/service/flag-sync/sync-multiplexer_test.go
  flagd/pkg/service/flag-sync/sync_service_test.go
  flagd/pkg/service/flag-sync/util_test.go
Labels: size:M

#1359 chore: update public schema
  docs/schema/v0/flags.json
  docs/schema/v0/targeting.json
Labels: size:M

#1360 chore: update playground
  docs/playground/playground.js
  playground-app/package-lock.json
  playground-app/package.json
Labels: size:XS

#1358 feat: added new grpc sync config option to allow setting max receive message size.
  core/pkg/sync/builder/syncbuilder.go
  core/pkg/sync/builder/syncbuilder_test.go
  core/pkg/sync/grpc/grpc_sync.go
  core/pkg/sync/grpc/grpc_sync_test.go
  core/pkg/sync/isync.go
  docs/reference/sync-configuration.md
Labels: size:M

#1370 chore: update otel example configurations
  docs/reference/monitoring.md
Labels: size:XS

#1366 feat: Support blob type sources and GCS as an example of such source.
  core/go.mod
  core/go.sum
  core/pkg/sync/blob/blob_sync.go
  core/pkg/sync/blob/blob_sync_test.go
  core/pkg/sync/blob/mock_blob.go
  core/pkg/sync/builder/syncbuilder.go
  core/pkg/sync/builder/syncbuilder_test.go
  core/pkg/sync/builder/utils.go
  core/pkg/sync/builder/utils_test.go
  core/pkg/sync/http/http_sync_test.go
  core/pkg/sync/http/mock/http.go
  core/pkg/sync/testing/mock_cron.go
  docs/concepts/syncs.md
  docs/reference/sync-configuration.md
Labels: size:XL
