Repository open-feature/flagd, pull requests merged in 2024-12, with the labels that each got.

#1448 feat: add context value flag
  Makefile
  core/pkg/service/iservice.go
  docs/reference/flag-definitions.md
  docs/reference/flagd-cli/flagd_start.md
  flagd/cmd/start.go
  flagd/pkg/runtime/from_config.go
  flagd/pkg/service/flag-evaluation/connect_service.go
  flagd/pkg/service/flag-evaluation/flag_evaluator.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_test.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_v2_test.go
  flagd/pkg/service/flag-evaluation/ofrep/handler.go
  flagd/pkg/service/flag-evaluation/ofrep/ofrep_service.go
  flagd/pkg/service/flag-evaluation/ofrep/ofrep_service_test.go
  flagd/pkg/service/flag-sync/handler.go
  flagd/pkg/service/flag-sync/sync_service.go
Labels: size:L

#1478 feat(spec): from grace attempts to grace period, plus connection info
  docs/reference/specifications/providers.md
Labels: size:M

#1494 build(renovate): Utilize default OpenFeature Renovate configuration
  renovate.json
Labels: size:S

#1477 docs: Add docs for s3 blobs
  docs/concepts/syncs.md
  docs/reference/sync-configuration.md
Labels: size:S
