Repository open-feature/flagd, pull requests merged in 2024-10, with the labels that each got.

#1421 docs: update gRPC custom resolver rfc proposal
  docs/reference/specifications/proposal/rfc-grpc-custom-name-resolver.md
Labels: size:XS

#1419 docs: fix typo
  docs/reference/openfeature-operator/overview.md
Labels: size:XS

#1426 ci: fix security scan input path
  .github/workflows/build.yaml
Labels: size:S

#1428 feat: support azure blob sync
  core/go.mod
  core/go.sum
  core/pkg/sync/blob/blob_sync.go
  core/pkg/sync/builder/syncbuilder.go
  core/pkg/sync/builder/syncbuilder_test.go
  core/pkg/sync/builder/utils.go
  core/pkg/sync/builder/utils_test.go
  docs/concepts/syncs.md
  docs/reference/flagd-cli/flagd_start.md
  docs/reference/sync-configuration.md
  flagd/cmd/start.go
Labels: size:L

#1431 chore: fix netlify doc publish
  netlify.toml
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: size:M

#1424 feat: added custom grpc resolver
  .github/workflows/build.yaml
  core/pkg/sync/builder/syncbuilder.go
  core/pkg/sync/builder/utils.go
  core/pkg/sync/grpc/grpc_sync.go
  core/pkg/sync/grpc/nameresolvers/envoy_resolver.go
  core/pkg/sync/grpc/nameresolvers/envoy_resolver_test.go
  docs/reference/sync-configuration.md
  flagd/go.sum
Labels: size:L

#1434 ci: fix license bundling command
  .github/workflows/release-please.yaml
Labels: size:XS

#1432 docs: update flagd provider specs
  .markdownlint-cli2.yaml
  docs/reference/monitoring.md
  docs/reference/specifications/in-process-providers.md
  docs/reference/specifications/providers.md
  docs/reference/specifications/rpc-providers.md
  mkdocs.yml
Labels: size:XL
