Repository open-feature/flagd, pull requests merged in 2024-05, with the labels that each got.

#1316 chore: fix unit tests and ensure their execution
  Makefile
  flagd/pkg/service/flag-evaluation/ofrep/ofrep_service_test.go
Labels: size:S

#1318 chore: update to fix unary bug in playground
  docs/playground/playground.js
  playground-app/package-lock.json
  playground-app/package.json
Labels: size:XS

#1315 chore: adapt telemetry setup error handling
  core/pkg/telemetry/builder.go
  core/pkg/telemetry/metrics.go
  core/pkg/telemetry/metrics_test.go
  flagd/pkg/runtime/from_config.go
  flagd/pkg/service/flag-evaluation/connect_service.go
  flagd/pkg/service/flag-evaluation/flag_evaluator.go
  flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go
  flagd/pkg/service/middleware/metrics/http_metrics.go
Labels: size:L
