Repository open-feature/flagd, pull requests merged in 2025-03, with the labels that each got.

#1589 feat: accept version numbers which are not strings
  core/pkg/evaluator/semver.go
  core/pkg/evaluator/semver_test.go
  flagd/pkg/service/flag-sync/test-cert/ca-cert.pem
  flagd/pkg/service/flag-sync/test-cert/gen.sh
  flagd/pkg/service/flag-sync/test-cert/server-cert.pem
  flagd/pkg/service/flag-sync/test-cert/server-key.pem
Labels: size:L

#1599 fix: incorrect metadata returned per source
  core/pkg/store/flags.go
  flagd/pkg/service/flag-sync/sync-multiplexer.go
  flagd/pkg/service/flag-sync/sync-multiplexer_test.go
  flagd/pkg/service/flag-sync/util_test.go
Labels: size:M

#1608 fix: incorrect comparison used for time
  core/pkg/sync/blob/blob_sync.go
Labels: size:XS

#1600 refactor: Refactor the cron function in http sync
  core/pkg/sync/http/http_sync.go
Labels: size:M
