Repository open-feature/flagd, pull requests merged in 2025-01, with the labels that each got.

#1501 feat: add ssl support to sync service (#1479)
  core/pkg/telemetry/builder.go
  flagd/pkg/service/flag-sync/sync_service.go
  flagd/pkg/service/flag-sync/sync_service_test.go
  flagd/pkg/service/flag-sync/test-cert/ca-cert.pem
  flagd/pkg/service/flag-sync/test-cert/gen.sh
  flagd/pkg/service/flag-sync/test-cert/server-cert.pem
  flagd/pkg/service/flag-sync/test-cert/server-ext.cnf
  flagd/pkg/service/flag-sync/test-cert/server-key.pem
  flagd/pkg/service/flag-sync/util_test.go
Labels: size:L

#1505 docs: flag and flag-set metadata
  docs/reference/flag-definitions.md
  docs/reference/specifications/providers.md
Labels: size:S

#1476 feat: support flag metadata
  core/pkg/evaluator/json.go
  core/pkg/evaluator/json_model.go
  core/pkg/evaluator/json_test.go
  core/pkg/model/flag.go
  core/pkg/store/flags.go
Labels: size:L

#1517 fix(sync): fixing missing handover of ssl configuration
  flagd/pkg/runtime/from_config.go
Labels: size:XS

#1516 fix: Skip flagd banner when non-console logger in use
  flagd-proxy/cmd/root.go
  flagd-proxy/main.go
  flagd/cmd/root.go
  flagd/main.go
Labels: size:M

#1525 feat: migrate file evaluation to own provider type
  docs/reference/specifications/providers.md
Labels: size:M

#1522 feat: support yaml in blob, file, and http syncs
  core/go.sum
  core/pkg/sync/blob/blob_sync.go
  core/pkg/sync/blob/blob_sync_test.go
  core/pkg/sync/file/filepath_sync.go
  core/pkg/sync/file/filepath_sync_test.go
  core/pkg/sync/http/http_sync.go
  core/pkg/sync/http/http_sync_test.go
  core/pkg/utils/convert_to_json.go
  core/pkg/utils/convert_to_json_test.go
  core/pkg/utils/yaml.go
  core/pkg/utils/yaml_test.go
  docs/concepts/syncs.md
  docs/reference/sync-configuration.md
Labels: size:XL
