Repository open-feature/flagd, pull requests merged in 2025-02, with the labels that each got.

#1547 fix: enable SBOM generation and provenance in release workflow
  .github/workflows/release-please.yaml
  docs/faq.md
Labels: size:M

#1550 docs: metadata conceptual doc
  docs/concepts/feature-flagging.md
  docs/reference/monitoring.md
Labels: size:XS

#1563 feat: Adding gRPC dial option override to grpc_sync.go
  core/pkg/sync/grpc/grpc_sync.go
Labels: size:M

#1553 docs: fix url for flags.json
  docs/reference/specifications/protos.md
Labels: size:XS

#1560 fix: add support for unix socket connection in sync service (#1518)
  docs/reference/flagd-cli/flagd_start.md
  docs/reference/specifications/providers.md
  flagd/cmd/start.go
  flagd/go.mod
  flagd/go.sum
  flagd/pkg/runtime/from_config.go
  flagd/pkg/service/flag-sync/sync_service.go
  flagd/pkg/service/flag-sync/sync_service_test.go
Labels: size:L
