Repository open-feature/flagd, pull requests merged in 2025-07, with the labels that each got.

#1660 docs(ADR): support flags with duplicate keys.
  docs/architecture-decisions/duplicate-flag-keys.md
Labels: size:L

#1634 docs(ADR): propose support for flag set selection
  docs/architecture-decisions/multiple-flag-set-support.md
Labels: size:L

#1680 fix: general err if targeting variant not in variants
  core/pkg/evaluator/json.go
  core/pkg/evaluator/legacy_fractional_test.go
Labels: size:XS

#1645 feat: Add support for HTTP eTag header and 304 no change response
  core/pkg/sync/http/http_sync.go
  core/pkg/sync/http/http_sync_test.go
  docs/concepts/syncs.md
Labels: size:L

#1694 chore: add back file-delete test
  CONTRIBUTING.md
  core/pkg/sync/file/filepath_sync_test.go
  core/pkg/sync/http/http_sync_test.go
Labels: size:M

#1693 feat: Add toggle for disabling getMetadata request
  docs/reference/flagd-cli/flagd_start.md
  flagd/cmd/start.go
  flagd/pkg/runtime/from_config.go
  flagd/pkg/service/flag-sync/handler.go
  flagd/pkg/service/flag-sync/handler_test.go
  flagd/pkg/service/flag-sync/sync_service.go
  flagd/pkg/service/flag-sync/sync_service_test.go
Labels: size:L
